DROP TABLE PERSONABATCH;

CREATE TABLE PERSONABATCH(
ID       NUMBER (10) NOT NULL,
NOMBRE VARCHAR2 (35) NOT NULL,
APEPAT VARCHAR2 (35) NOT NULL,
TEL    VARCHAR2 (35) NOT NULL,
CONSTRAINT PERSONABATCH_PK PRIMARY KEY (ID));

COMMIT;